#!/bin/bash
#
# Similar to demo01 but formats the output using IEEE's journal style. Also:
#   * Numbers sections
#   * Substitutes links to URLs with footnotes
#   * Converts cross-references using /autoref
#   * Fixes longtable so it can be used in two-column environment
#   * Selects 'Times' as the font family
#   * Passes 'conference' class option

docker run \
  --rm \
  --workdir="/root" \
  -v `pwd`/../vendor/pandoc-templates:/root/.pandoc/templates \
  -v `pwd`/../vendor/latex-files:/root/texmf/tex/latex \
  -v `pwd`/../vendor/bibtools/ieee.csl:/root/ieee.csl \
  -v `pwd`/../vendor/bibfile/zotero.bib:/root/citations.bib \
  -v `pwd`/../main.md:/root/main.md \
  -v `pwd`/../figures:/root/figures \
  -v `pwd`/out:/root/out \
  ivotron/pandoc:1.13.2 \
    --bibliography=citations.bib \
    --csl=ieee.csl \
    --highlight-style tango \
    --metadata=documentclass:ieeetran \
    --metadata=ieeetran:true \
    --metadata=classoption:conference \
    --metadata=fontfamily:times \
    --metadata=numbersections:true \
    --metadata=substitute-hyperref:true \
    --metadata=twocolumn-longtable:true \
    --metadata=links-as-notes:true \
    --output=out/demo05.pdf main.md 2> build.log

if [ $? != "0" ] ; then
  echo "ERROR: check build.log for details"
  exit 1
fi

echo "SUCCESS: check out/ folder for output"

exit 0

