#!/bin/bash
#
# Generate LaTeX source from markdown, then a PDF using pdflatex. This is useful 
# for doing tweaks at the LaTeX level before generating a PDF.

docker run \
  --rm \
  --workdir="/root" \
  -v `pwd`/../vendor/pandoc-templates:/root/.pandoc/templates \
  -v `pwd`/../vendor/bibfile/zotero.bib:/root/citations.bib \
  -v `pwd`/../main.md:/root/main.md \
  -v `pwd`/../figures:/root/figures \
  -v `pwd`/out:/root/out \
  ivotron/pandoc:1.13.2 \
    --standalone \
    --highlight-style tango \
    --bibliography=citations.bib \
    --output=out/demo06.tex main.md 2> build.log

if [ $? != "0" ] ; then
  echo "ERROR: check build.log for details"
  exit 1
fi

docker run \
  --rm \
  --workdir="/root" \
  --entrypoint="/usr/bin/pdflatex" \
  -v `pwd`/../figures:/root/figures \
  -v `pwd`/out/demo06.tex:/root/demo06.tex \
  -v `pwd`/out:/root/out \
  ivotron/pandoc:1.13.2 \
    -output-directory=out/ demo06.tex 2> build.log

if [ $? != "0" ] ; then
  echo "ERROR: check build.log for details"
  exit 1
fi

echo "SUCCESS: check out/ folder for output"

exit 0
